site_name: hexif-pyutils
site_description: A collection of useful Python utilities

theme:
  name: material

  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono

  icon:
    repo: fontawesome/brands/github

plugins:
  - search

  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py

  - literate-nav:
      nav_file: reference/SUMMARY.md

  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_object_full_path: false
            members_order: source