[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "hexif-pyutils"
version = "1.2.0"
description = "Super simple python utility library"
readme = "README.md"
requires-python = ">=3.9"

authors = [{name = "HeXif"}]

license = "MIT"

keywords = [
    "utilties",
    "utils",
    "python",
    "helpers"
]

[project.urls]
Documentation = "https://hexif-pyutils.readthedocs.io/"
Homepage = "https://github.com/xHeXifx/hexif-pyutils"
Repository = "https://github.com/xHeXifx/hexif-pyutils"
Issues = "https://github.com/xHeXifx/hexif-pyutils/issues"

[project.optional-dependencies]
docs = [
    "mkdocs-material",
    "mkdocstrings[python]",
    "mkdocs-gen-files",
    "mkdocs-literate-nav",
]

[tool.setuptools.packages.find]
include = ["utils*"]
